name: StudyLife
version: '1.0-SNAPSHOT'
main: com.yaesaraki.studyLife.StudyLifePlugin
api-version: '1.21'
folia-supported: true
commands:
  focus:
    description: 控制专注番茄钟
    usage: /focus [start|stop]